// <auto-generated />
using System;
using Education.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Education.Persistence.Migrations
{
    [DbContext(typeof(EducationDbContext))]
    [Migration("20220603001047_EducationMigrationInicial")]
    partial class EducationMigrationInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Education.Domain.Curso", b =>
                {
                    b.Property<Guid>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Precio")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CursoId");

                    b.ToTable("Curso");

                    b.HasData(
                        new
                        {
                            CursoId = new Guid("0ec9ac4e-5f04-4d3c-be03-94dfea4ca5a7"),
                            Descripcion = "Curso de C# básico",
                            FechaCreacion = new DateTime(2022, 6, 2, 19, 10, 47, 127, DateTimeKind.Local).AddTicks(6418),
                            FechaPublicacion = new DateTime(2024, 6, 2, 19, 10, 47, 127, DateTimeKind.Local).AddTicks(6431),
                            Precio = 56m,
                            Titulo = "C# desde cero hasta avanzado"
                        },
                        new
                        {
                            CursoId = new Guid("db4f0e44-ae21-4259-8bef-92d3cef38dca"),
                            Descripcion = "Master en Java Spring desde las raices",
                            FechaCreacion = new DateTime(2022, 6, 2, 19, 10, 47, 127, DateTimeKind.Local).AddTicks(6438),
                            FechaPublicacion = new DateTime(2024, 6, 2, 19, 10, 47, 127, DateTimeKind.Local).AddTicks(6439),
                            Precio = 25m,
                            Titulo = "Curso de Java"
                        },
                        new
                        {
                            CursoId = new Guid("1595c01e-5300-4239-85ea-604ca757da13"),
                            Descripcion = "Master en Unit Test con CQRS",
                            FechaCreacion = new DateTime(2022, 6, 2, 19, 10, 47, 127, DateTimeKind.Local).AddTicks(6441),
                            FechaPublicacion = new DateTime(2024, 6, 2, 19, 10, 47, 127, DateTimeKind.Local).AddTicks(6442),
                            Precio = 1000m,
                            Titulo = "Curso de Unit Test para NET Core"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
